### ISSUE TITLE
dev docs

### ISSUE THREAD

**Issue by malithmcr** [andybelldesign/personalsit.es#160]
Hey @andybelldesign, 

Thanks for the great website. I'd like to help you with styling and add improvements to this project. But I need help to run this project on my local. I tried to run `npm install && npx serve` but it just shows all the files list in the browser and that's it.  

:) :)

**Comment by andybelldesign** [comment]
Hi there. This project will be getting a proper design job done on it soon. It’s currently a half an hour, quick job.

Thanks for the offer of help though.
