### ISSUE TITLE
Remove need for contributors to add ‘sites’ tag

### ISSUE THREAD

**Issue by paulrobertlloyd** [andybelldesign/personalsit.es#83]
I’m sure you’re probably aware of this, but with a directory data file and using the [data deep merge feature](https://www.11ty.io/docs/config/#data-deep-merge), it’s possible to add the `sites` tag as a default, thus saving contributors from having to worry about it. Just a thought! Thanks for putting this little directory together, it’s a great idea!

**Comment by andybelldesign** [comment]
Very fair point. This is something I was only made aware of after I slung this project together. More than happy to accept a PR if you've got some time?
